os: linux
dist: bionic
language: python
install: skip
script: skip
deploy:
  provider: pypi
  user: __token__
  password:
    secure: HpHlmB7MOn6I5XKyJ//bTuJDJzH2F6WVHdjuKbhxWU8lFIwaCAwLGqOz7MZy9H7SIP/FcZrTALev0q71piqyDvUjCkBdOgkimMcSfUAvFHgdWoia0yTr1bxR0hXHy38pcfh7HQkxSyHzIKfBBuqTzn8H2JwRzc5p84PL5QlvchSVofkloridmLCWUijAPJZ2d+EcizdtEtJBrmSxxOyAHkikmlxOXoyZNBLkknb4oNBG9/yMDwTPhMIp3WbTkqnUlf2w7Vk8T5UAPilFPVtGhr8aPMFaBirVX92o1mFG3waVETu9icKmY/+nRM77+b3DhridLIBLxUMafCYacblzG+KWYrG8HgfLLXzVncUrbuKOwl+nvS6P6a2NqZVmPFjz8Yx+N91bexpXLJLSnXKh+LP/FfxRoD68miJE9BI9R6UUfB4kMC9uH/mxVQVbN72LMCDLl/eRfrXerSbytsquNx25RBn7QZUQ1M7bX97ICxnp9/r6z9mZ0u8jzpnxC82WPPtT6EdydhtKskDMrIdQbXypEzSZ4agFLMr8ltZAToYatFzwCHvw4r2dnkxuHbO1r3drMo1edn65GgN+IADWMVIcGqNVvNDoTkBY3DM/1Z2JctG2HtoMwud3hmQjbiEFmVDleGRi/1a+LJybDNQCb0wfe75Lfen8przDxZPAbu4=
  on:
    tags: true
